script:
  - echo "${KEY}" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null "${CONN}" 'git -C /var/www/test_www pull'
after_script:
  - rm ~/.ssh/id_rsa
