script:
#  - echo "${KEY}" > id_rsa.nonl
#  - cat id_rsa.nonl | tr '~' '\n' > id_rsa
#  - md5sum id_rsa
#  - chmod 600 id_rsa
  - ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null "${CONN}" 'git -C /var/www/test_www pull'

